const MOCK_JOBS = [
  // ── IT/개발 ──────────────────────────────────────────
  {
    id: 1,
    company: "카카오",
    logoText: "K",
    gradient: "linear-gradient(145deg, #FEE500 0%, #FF6B35 100%)",
    category: "IT/개발",
    employmentType: "정규직",
    title: "프론트엔드 개발자",
    department: "플랫폼개발팀",
    location: "판교",
    locationGroup: "경기",
    salary: "5,000 ~ 8,000만원",
    salaryMin: 5000,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    requirements: ["React 기반 프로덕트 개발 경험 3년 이상", "TypeScript 실무 경험", "성능 최적화 경험"],
    preferred: ["GraphQL/REST API 설계 경험", "디자인 시스템 구축 경험", "오픈소스 기여 경험"],
    mainTasks: ["카카오 핵심 서비스 프론트엔드 개발", "사용자 경험 개선 및 성능 최적화", "디자인 시스템 구축 및 운영"],
    benefits: ["유연근무", "재택근무", "스톡옵션", "사내 카페"],
    companyInfo: "카카오는 국내 1위 모바일 플랫폼으로, 카카오톡을 비롯한 다양한 서비스를 운영하고 있습니다.",
    deadline: "2026-04-15",
    dDay: null,
    views: 12453,
    likes: 234,
    saved: 89,
    source: "카카오 채용",
    url: "https://careers.kakao.com",
  },
  {
    id: 2,
    company: "네이버",
    logoText: "N",
    gradient: "linear-gradient(145deg, #03C75A 0%, #009944 100%)",
    category: "IT/개발",
    employmentType: "정규직",
    title: "백엔드 개발자 (Java)",
    department: "검색플랫폼개발",
    location: "분당",
    locationGroup: "경기",
    salary: "4,800 ~ 7,500만원",
    salaryMin: 4800,
    experience: "경력 2년 이상",
    experienceLevel: "경력",
    skills: ["Java", "Spring Boot", "Kafka", "MySQL"],
    requirements: ["Java/Spring 기반 백엔드 개발 경험 2년 이상", "RDBMS 설계 및 최적화 경험", "RESTful API 설계 경험"],
    preferred: ["Kafka 활용 경험", "MSA 아키텍처 경험", "대용량 트래픽 처리 경험"],
    mainTasks: ["네이버 검색 플랫폼 백엔드 개발", "대용량 트래픽 처리 시스템 설계", "MSA 기반 서비스 개발 및 운영"],
    benefits: ["유연근무", "건강검진 지원", "자기개발비", "사내 복지몰"],
    companyInfo: "네이버는 대한민국 1위 검색 포털로, AI·클라우드·커머스 등 다양한 분야로 사업을 확장하고 있습니다.",
    deadline: "2026-04-30",
    dDay: null,
    views: 9876,
    likes: 187,
    saved: 67,
    source: "네이버 채용",
    url: "https://recruit.navercorp.com",
  },
  {
    id: 3,
    company: "토스",
    logoText: "T",
    gradient: "linear-gradient(145deg, #0064FF 0%, #4B9EFF 100%)",
    category: "IT/개발",
    employmentType: "정규직",
    title: "iOS 개발자",
    department: "토스앱",
    location: "강남",
    locationGroup: "서울",
    salary: "6,000 ~ 10,000만원",
    salaryMin: 6000,
    experience: "경력 4년 이상",
    experienceLevel: "경력",
    skills: ["Swift", "UIKit", "SwiftUI", "RxSwift"],
    requirements: ["Swift 기반 iOS 앱 개발 4년 이상", "UIKit/SwiftUI 실무 경험", "App Store 배포 경험"],
    preferred: ["금융 앱 개발 경험", "RxSwift/Combine 활용 경험", "MVVM 아키텍처 경험"],
    mainTasks: ["토스 앱 iOS 핵심 기능 개발", "금융 서비스 UI/UX 구현", "앱 성능 최적화 및 안정성 개선"],
    benefits: ["스톡옵션", "무제한 연차", "원격근무", "최고 연봉 보장"],
    companyInfo: "토스(Viva Republica)는 금융의 모든 것을 쉽게 만드는 핀테크 유니콘으로, 2800만 명의 사용자를 보유하고 있습니다.",
    deadline: "2026-05-01",
    dDay: null,
    views: 18920,
    likes: 412,
    saved: 203,
    source: "토스 채용",
    url: "https://toss.im/career",
  },
  {
    id: 4,
    company: "삼성전자",
    logoText: "S",
    gradient: "linear-gradient(145deg, #1428A0 0%, #2B5CE6 100%)",
    category: "데이터/AI",
    employmentType: "정규직",
    title: "AI 연구원",
    department: "삼성리서치",
    location: "서초",
    locationGroup: "서울",
    salary: "협의 가능",
    salaryMin: 0,
    experience: "박사 학위 소지자",
    experienceLevel: "경력",
    skills: ["PyTorch", "TensorFlow", "Python", "논문 경험"],
    requirements: ["AI/ML 관련 박사 학위 소지자", "SCI급 논문 2편 이상", "딥러닝 프레임워크 실무 경험"],
    preferred: ["온디바이스 AI 연구 경험", "특허 출원 경험", "글로벌 AI 학회 발표 경험"],
    mainTasks: ["온디바이스 AI 핵심 알고리즘 연구", "갤럭시 AI 서비스 모델 개발", "논문 작성 및 특허 출원"],
    benefits: ["연구비 지원", "해외 학회 참가", "주거 지원", "자녀 학자금"],
    companyInfo: "삼성전자는 글로벌 IT 리더로, 반도체·스마트폰·AI 등 첨단 기술 분야를 선도하고 있습니다.",
    deadline: "2026-04-20",
    dDay: null,
    views: 7341,
    likes: 156,
    saved: 94,
    source: "삼성 채용",
    url: "https://www.samsung.com/sec/aboutsamsung/careers",
  },
  {
    id: 5,
    company: "쿠팡",
    logoText: "C",
    gradient: "linear-gradient(145deg, #FF0000 0%, #FF6B6B 100%)",
    category: "IT/개발",
    employmentType: "정규직",
    title: "데이터 엔지니어",
    department: "데이터플랫폼",
    location: "잠실",
    locationGroup: "서울",
    salary: "5,500 ~ 9,000만원",
    salaryMin: 5500,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["Spark", "Airflow", "Python", "AWS", "Redshift"],
    requirements: ["Python/SQL 기반 데이터 파이프라인 구축 3년 이상", "Spark/Flink 활용 경험", "클라우드 환경(AWS/GCP) 경험"],
    preferred: ["실시간 데이터 처리(Kafka, Flink) 경험", "데이터 품질 관리 체계 구축 경험"],
    mainTasks: ["쿠팡 데이터 파이프라인 설계 및 구축", "실시간 데이터 처리 시스템 운영", "데이터 품질 모니터링 체계 구축"],
    benefits: ["RSU 지급", "유연근무", "헬스케어 지원", "간식 제공"],
    companyInfo: "쿠팡은 한국 최대의 이커머스 플랫폼으로, 로켓배송을 통해 물류 혁신을 이끌고 있습니다.",
    deadline: "2026-04-10",
    dDay: null,
    views: 8102,
    likes: 143,
    saved: 58,
    source: "쿠팡 채용",
    url: "https://www.coupang.jobs",
  },
  // ── 신입/인턴 공고 ─────────────────────────────────
  {
    id: 6,
    company: "카카오",
    logoText: "K",
    gradient: "linear-gradient(145deg, #FEE500 0%, #FF6B35 100%)",
    category: "IT/개발",
    employmentType: "인턴",
    title: "프론트엔드 개발 인턴",
    department: "플랫폼개발팀",
    location: "판교",
    locationGroup: "경기",
    salary: "월 250만원",
    salaryMin: 3000,
    experience: "신입/인턴",
    experienceLevel: "신입",
    skills: ["JavaScript", "React", "HTML/CSS"],
    requirements: ["컴퓨터공학 또는 관련 전공 재학/졸업생", "JavaScript 기초 이해", "팀 프로젝트 경험"],
    preferred: ["React 사용 경험", "개인 포트폴리오 보유", "오픈소스 기여 경험"],
    mainTasks: ["카카오 서비스 프론트엔드 기능 개발 보조", "버그 수정 및 코드 리뷰 참여", "사내 개발 문화 경험"],
    benefits: ["정규직 전환 기회", "멘토링 프로그램", "사내 교육", "식대 지원"],
    companyInfo: "카카오는 국내 1위 모바일 플랫폼으로, 매년 우수 인턴을 정규직으로 전환합니다.",
    deadline: "2026-04-20",
    dDay: null,
    views: 15320,
    likes: 389,
    saved: 241,
    source: "카카오 채용",
    url: "https://careers.kakao.com",
  },
  {
    id: 7,
    company: "네이버",
    logoText: "N",
    gradient: "linear-gradient(145deg, #03C75A 0%, #009944 100%)",
    category: "IT/개발",
    employmentType: "신입",
    title: "서버 개발자 (신입)",
    department: "개발플랫폼",
    location: "분당",
    locationGroup: "경기",
    salary: "4,000만원 ~ (신입 초봉)",
    salaryMin: 4000,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["Java", "Spring", "MySQL", "Git"],
    requirements: ["컴퓨터공학 또는 관련 전공 졸업(예정)자", "Java/Spring 기초 역량", "알고리즘 문제 해결 능력"],
    preferred: ["인턴십 경험", "개인 프로젝트 GitHub 보유", "ICPC/BOJ 플래티넘 이상"],
    mainTasks: ["서비스 백엔드 개발 참여", "코드 리뷰 및 기술 문서 작성", "온보딩 교육 프로그램 참여"],
    benefits: ["유연근무", "건강검진", "자기개발비", "사내 복지몰"],
    companyInfo: "네이버는 신입 개발자도 실제 서비스에 기여할 수 있는 문화를 지향합니다.",
    deadline: "2026-05-15",
    dDay: null,
    views: 21480,
    likes: 567,
    saved: 312,
    source: "네이버 채용",
    url: "https://recruit.navercorp.com",
  },
  {
    id: 8,
    company: "토스",
    logoText: "T",
    gradient: "linear-gradient(145deg, #0064FF 0%, #4B9EFF 100%)",
    category: "IT/개발",
    employmentType: "인턴",
    title: "Android 개발 인턴",
    department: "모바일개발",
    location: "강남",
    locationGroup: "서울",
    salary: "월 300만원",
    salaryMin: 3600,
    experience: "신입/인턴",
    experienceLevel: "신입",
    skills: ["Kotlin", "Android", "Jetpack Compose"],
    requirements: ["Android 개발 경험 (개인 프로젝트 포함)", "Kotlin 기초 이해", "Git 사용 경험"],
    preferred: ["Play Store 출시 앱 보유", "Jetpack Compose 경험", "금융 앱 관심"],
    mainTasks: ["토스 앱 Android 기능 개발 보조", "QA 테스트 및 버그 수정", "개발팀 코드 리뷰 참여"],
    benefits: ["정규직 전환 기회", "최고 수준의 인턴 처우", "무료 식사", "개발 장비 지원"],
    companyInfo: "토스는 인턴에게도 실제 프로덕트 개발 기회를 제공하며, 우수 인턴은 정규직으로 전환됩니다.",
    deadline: "2026-04-25",
    dDay: null,
    views: 18750,
    likes: 445,
    saved: 267,
    source: "토스 채용",
    url: "https://toss.im/career",
  },
  // ── 디자인 ─────────────────────────────────────────
  {
    id: 9,
    company: "배달의민족",
    logoText: "B",
    gradient: "linear-gradient(145deg, #2AC1BC 0%, #0079C1 100%)",
    category: "디자인",
    employmentType: "정규직",
    title: "UX 디자이너",
    department: "프로덕트디자인",
    location: "송파",
    locationGroup: "서울",
    salary: "4,500 ~ 7,000만원",
    salaryMin: 4500,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["Figma", "프로토타입", "사용자 리서치", "디자인 시스템"],
    requirements: ["UX/UI 디자인 실무 경험 3년 이상", "Figma 능숙한 사용", "포트폴리오 제출 필수"],
    preferred: ["앱/웹 서비스 디자인 경험", "디자인 시스템 구축 경험", "사용자 리서치 경험"],
    mainTasks: ["배달앱 사용자 경험 설계 및 개선", "디자인 시스템 구축 및 가이드라인 작성", "사용자 리서치 기반 문제 정의"],
    benefits: ["유연근무", "식대 지원", "도서비", "해외 컨퍼런스"],
    companyInfo: "우아한형제들(배달의민족)은 대한민국 1위 배달 플랫폼으로, 독창적인 디자인 문화로 유명합니다.",
    deadline: "2026-04-05",
    dDay: null,
    views: 5678,
    likes: 98,
    saved: 44,
    source: "우아한형제들 채용",
    url: "https://career.woowahan.com",
  },
  {
    id: 10,
    company: "무신사",
    logoText: "M",
    gradient: "linear-gradient(145deg, #1a1a1a 0%, #404040 100%)",
    category: "디자인",
    employmentType: "신입",
    title: "브랜드 디자이너 (신입)",
    department: "브랜드디자인",
    location: "홍대",
    locationGroup: "서울",
    salary: "3,200 ~ 4,000만원",
    salaryMin: 3200,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["Photoshop", "Illustrator", "Figma", "브랜딩"],
    requirements: ["시각디자인 또는 관련 전공 졸업(예정)자", "Adobe CC 툴 능숙", "포트폴리오 필수"],
    preferred: ["패션/라이프스타일 브랜드 관심", "타이포그래피 감각", "영상 편집 경험"],
    mainTasks: ["무신사 브랜드 비주얼 디자인 작업", "캠페인 콘텐츠 제작", "온라인 배너/SNS 콘텐츠 디자인"],
    benefits: ["패션 할인 혜택", "자유로운 복장", "간식바", "자기개발비"],
    companyInfo: "무신사는 한국 최대 패션 플랫폼으로, 트렌디한 브랜드 문화를 만들어가고 있습니다.",
    deadline: "2026-04-22",
    dDay: null,
    views: 8920,
    likes: 212,
    saved: 108,
    source: "무신사 채용",
    url: "https://about.musinsa.com/careers",
  },
  // ── 기획/PM ────────────────────────────────────────
  {
    id: 11,
    company: "직방",
    logoText: "직",
    gradient: "linear-gradient(145deg, #5AC045 0%, #3D9C2F 100%)",
    category: "기획/PM",
    employmentType: "정규직",
    title: "프로덕트 매니저 (PM)",
    department: "부동산플랫폼",
    location: "강남",
    locationGroup: "서울",
    salary: "4,500 ~ 7,500만원",
    salaryMin: 4500,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["데이터 분석", "SQL", "스크럼", "사용자 인터뷰", "로드맵"],
    requirements: ["프로덕트 매니저 또는 서비스 기획 3년 이상", "데이터 기반 의사결정 경험", "개발/디자인팀 협업 경험"],
    preferred: ["부동산/핀테크 도메인 이해", "SQL 활용 능력", "OKR/KPI 관리 경험"],
    mainTasks: ["부동산 매물 검색/추천 서비스 기획", "데이터 기반 제품 의사결정", "개발/디자인팀과 협업하여 제품 출시"],
    benefits: ["부동산 정보 혜택", "유연근무", "자기개발비", "점심 지원"],
    companyInfo: "직방은 국내 1위 부동산 정보 플랫폼으로, 스마트홈 솔루션으로도 사업 영역을 확장하고 있습니다.",
    deadline: "2026-04-28",
    dDay: null,
    views: 4560,
    likes: 91,
    saved: 47,
    source: "직방 채용",
    url: "https://zigbang.recruiter.co.kr",
  },
  {
    id: 12,
    company: "당근마켓",
    logoText: "당",
    gradient: "linear-gradient(145deg, #FF7E36 0%, #FF4B00 100%)",
    category: "기획/PM",
    employmentType: "신입",
    title: "서비스 기획자 (신입)",
    department: "로컬비즈팀",
    location: "역삼",
    locationGroup: "서울",
    salary: "3,500 ~ 4,500만원",
    salaryMin: 3500,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["서비스 기획", "와이어프레임", "데이터 분석", "사용자 조사"],
    requirements: ["서비스/앱 기획 역량 보유자", "논리적인 사고와 문서 작성 능력", "사용자 관점의 문제 발굴 능력"],
    preferred: ["인턴십 또는 스타트업 경험", "Figma/Zeplin 사용 경험", "SQL 기초 지식"],
    mainTasks: ["당근마켓 로컬 비즈니스 서비스 기획", "사용자 리서치 및 데이터 분석", "개발/디자인팀과 스프린트 참여"],
    benefits: ["자율출퇴근", "원격근무", "점심 지원", "도서 지원"],
    companyInfo: "당근마켓은 한국의 대표 로컬 커뮤니티 플랫폼으로, 수평적인 문화와 자율성으로 유명합니다.",
    deadline: "2026-05-10",
    dDay: null,
    views: 12340,
    likes: 298,
    saved: 176,
    source: "당근마켓 채용",
    url: "https://about.daangn.com/jobs",
  },
  // ── 마케팅 ─────────────────────────────────────────
  {
    id: 13,
    company: "CJ ENM",
    logoText: "CJ",
    gradient: "linear-gradient(145deg, #E31837 0%, #FF6B6B 100%)",
    category: "마케팅",
    employmentType: "정규직",
    title: "디지털 마케터",
    department: "마케팅전략팀",
    location: "상암",
    locationGroup: "서울",
    salary: "4,000 ~ 6,000만원",
    salaryMin: 4000,
    experience: "경력 2년 이상",
    experienceLevel: "경력",
    skills: ["SNS 마케팅", "퍼포먼스 마케팅", "Google Analytics", "Meta Ads"],
    requirements: ["디지털 마케팅 실무 경험 2년 이상", "Google/Meta 광고 집행 경험", "데이터 분석 역량"],
    preferred: ["엔터테인먼트/미디어 업종 경험", "CRM 마케팅 경험", "영상 콘텐츠 마케팅 경험"],
    mainTasks: ["CJ ENM 채널·브랜드 디지털 마케팅 기획 및 집행", "퍼포먼스 캠페인 기획·운영 및 성과 분석", "SNS 채널 운영 및 팬덤 마케팅 전략 수립"],
    benefits: ["유연근무", "문화생활 지원", "건강검진", "자기개발비"],
    companyInfo: "CJ ENM은 tvN, OCN, Mnet 등을 운영하는 국내 최대 엔터테인먼트 미디어 그룹입니다.",
    deadline: "2026-04-18",
    dDay: null,
    views: 6870,
    likes: 142,
    saved: 78,
    source: "CJ 채용",
    url: "https://careers.cj.net",
  },
  {
    id: 14,
    company: "오늘의집",
    logoText: "O",
    gradient: "linear-gradient(145deg, #46C8F5 0%, #2B9ED4 100%)",
    category: "마케팅",
    employmentType: "신입",
    title: "콘텐츠 마케터 (신입)",
    department: "마케팅팀",
    location: "강남",
    locationGroup: "서울",
    salary: "3,200 ~ 4,000만원",
    salaryMin: 3200,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["콘텐츠 기획", "카피라이팅", "인스타그램", "블로그"],
    requirements: ["콘텐츠 제작 경험 (SNS, 블로그 등)", "트렌드에 대한 민감성", "창의적 글쓰기 능력"],
    preferred: ["인테리어/라이프스타일 관심", "포토샵/Canva 활용 능력", "인플루언서/유튜브 콘텐츠 기획 경험"],
    mainTasks: ["오늘의집 SNS 채널 콘텐츠 기획·제작", "인테리어 트렌드 리서치 및 콘텐츠화", "블로그·카카오채널 등 운영 보조"],
    benefits: ["인테리어 할인", "원격근무", "반려동물 동반", "유연근무"],
    companyInfo: "오늘의집은 국내 1위 홈 인테리어 플랫폼으로, 커뮤니티와 커머스를 결합한 독창적인 서비스를 운영합니다.",
    deadline: "2026-05-05",
    dDay: null,
    views: 9450,
    likes: 231,
    saved: 138,
    source: "오늘의집 채용",
    url: "https://bucketplace.career.greetinghr.com",
  },
  {
    id: 15,
    company: "야놀자",
    logoText: "Y",
    gradient: "linear-gradient(145deg, #FF4081 0%, #FF80AB 100%)",
    category: "마케팅",
    employmentType: "인턴",
    title: "마케팅 인턴 (퍼포먼스)",
    department: "그로스마케팅팀",
    location: "강남",
    locationGroup: "서울",
    salary: "월 220만원",
    salaryMin: 2640,
    experience: "신입/인턴",
    experienceLevel: "신입",
    skills: ["GA4", "Meta Ads", "Excel", "데이터 분석"],
    requirements: ["마케팅 또는 통계 관련 전공 재학/졸업생", "Excel/Sheets 활용 가능", "수치 분석에 대한 관심"],
    preferred: ["퍼포먼스 마케팅 교육 이수 경험", "Google Analytics 자격증", "여행/숙박 서비스 사용 경험"],
    mainTasks: ["퍼포먼스 마케팅 캠페인 보조 업무", "광고 데이터 수집 및 리포팅", "A/B 테스트 기획 참여"],
    benefits: ["정규직 전환 기회", "국내 호텔 할인", "자기개발비", "식대"],
    companyInfo: "야놀자는 국내 1위 여가 플랫폼으로, 글로벌 SaaS 사업으로 빠르게 성장 중입니다.",
    deadline: "2026-04-08",
    dDay: null,
    views: 7230,
    likes: 178,
    saved: 92,
    source: "야놀자 채용",
    url: "https://yanolja.career.greetinghr.com",
  },
  // ── 영업 ───────────────────────────────────────────
  {
    id: 16,
    company: "삼성생명",
    logoText: "삼",
    gradient: "linear-gradient(145deg, #003087 0%, #0057B8 100%)",
    category: "영업",
    employmentType: "정규직",
    title: "B2B 영업 전문가",
    department: "기업영업본부",
    location: "여의도",
    locationGroup: "서울",
    salary: "4,000 ~ 7,000만원 (인센티브 별도)",
    salaryMin: 4000,
    experience: "경력 2년 이상",
    experienceLevel: "경력",
    skills: ["B2B 영업", "고객 관계 관리", "계약 협상", "제안서 작성"],
    requirements: ["B2B 영업 또는 금융 세일즈 경험 2년 이상", "고객 발굴 및 니즈 분석 역량", "프레젠테이션 능력"],
    preferred: ["기업 보험/금융 상품 지식", "법인 영업 경험", "영어 비즈니스 커뮤니케이션"],
    mainTasks: ["대기업·중소기업 단체보험 영업", "신규 고객 발굴 및 장기 관계 유지", "맞춤형 금융 솔루션 제안 및 계약 체결"],
    benefits: ["고성과 인센티브", "유연근무", "건강검진", "퇴직연금"],
    companyInfo: "삼성생명은 국내 1위 생명보험사로, 체계적인 영업 지원 시스템과 성과 기반 보상 체계를 운영합니다.",
    deadline: "2026-04-30",
    dDay: null,
    views: 3240,
    likes: 54,
    saved: 29,
    source: "삼성생명 채용",
    url: "https://www.samsunglife.com/individual/others/career",
  },
  {
    id: 17,
    company: "SK텔레콤",
    logoText: "SK",
    gradient: "linear-gradient(145deg, #E51F2D 0%, #FF5252 100%)",
    category: "영업",
    employmentType: "신입",
    title: "기업고객 영업직 (신입)",
    department: "엔터프라이즈사업부",
    location: "을지로",
    locationGroup: "서울",
    salary: "4,200만원 (신입 초봉)",
    salaryMin: 4200,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["커뮤니케이션", "문서 작성", "고객 서비스", "Excel"],
    requirements: ["4년제 대학교 졸업(예정)자", "적극적인 커뮤니케이션 능력", "서비스 마인드"],
    preferred: ["영업/마케팅 관련 인턴 경험", "통신/IT 서비스 관심", "제2외국어 능력"],
    mainTasks: ["중소기업 대상 ICT 솔루션 영업", "고객 니즈 파악 및 맞춤 제안", "기존 고객 유지 및 업셀링"],
    benefits: ["복지포인트", "통신 요금 감면", "건강검진", "사내 동호회"],
    companyInfo: "SK텔레콤은 대한민국 1위 이동통신사로, AI·반도체·메타버스 등 미래 사업을 선도하고 있습니다.",
    deadline: "2026-04-25",
    dDay: null,
    views: 5890,
    likes: 102,
    saved: 61,
    source: "SK그룹 채용",
    url: "https://careers.sktelecom.com",
  },
  // ── 재무/회계 ───────────────────────────────────────
  {
    id: 18,
    company: "카카오페이",
    logoText: "KP",
    gradient: "linear-gradient(145deg, #3617CE 0%, #6C47FF 100%)",
    category: "재무/회계",
    employmentType: "정규직",
    title: "재무 분석가",
    department: "재무전략팀",
    location: "판교",
    locationGroup: "경기",
    salary: "5,000 ~ 8,000만원",
    salaryMin: 5000,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["재무 모델링", "Excel", "Python", "SQL", "회계"],
    requirements: ["경영학/회계학 전공 및 재무 실무 3년 이상", "재무제표 분석 능력", "CPA 또는 CFA 자격증 우대"],
    preferred: ["핀테크/금융 업종 경험", "Python/R 기반 데이터 분석", "IR 경험"],
    mainTasks: ["사업 부문별 재무 성과 분석 및 리포팅", "예산 수립 및 실적 관리", "투자자 대상 IR 자료 작성"],
    benefits: ["스톡옵션", "원격근무", "금융 서비스 혜택", "건강검진"],
    companyInfo: "카카오페이는 간편결제·보험·투자를 아우르는 국내 1위 핀테크 플랫폼입니다.",
    deadline: "2026-05-10",
    dDay: null,
    views: 3870,
    likes: 76,
    saved: 42,
    source: "카카오페이 채용",
    url: "https://kakaopay.com/careers",
  },
  {
    id: 19,
    company: "삼일회계법인",
    logoText: "PwC",
    gradient: "linear-gradient(145deg, #D93025 0%, #FF6B6B 100%)",
    category: "재무/회계",
    employmentType: "신입",
    title: "회계사 (신입 · CPA 합격자)",
    department: "감사본부",
    location: "여의도",
    locationGroup: "서울",
    salary: "5,500만원 ~ (CPA 합격자)",
    salaryMin: 5500,
    experience: "신입 (CPA 자격 필수)",
    experienceLevel: "신입",
    skills: ["회계감사", "IFRS", "재무제표 분석", "세무"],
    requirements: ["공인회계사(CPA) 합격자", "회계/세무 기초 지식", "팀워크 및 커뮤니케이션 능력"],
    preferred: ["Big4 인턴십 경험", "영어 능통자", "데이터 분석 능력"],
    mainTasks: ["상장사 및 대기업 회계감사 수행", "재무제표 작성 및 검토", "클라이언트 자문 업무 보조"],
    benefits: ["CPA 수험 지원", "해외 연수 기회", "경쟁력 있는 초봉", "건강검진"],
    companyInfo: "삼일회계법인(PwC Korea)은 국내 최대 Big4 회계법인 중 하나로, 글로벌 네트워크를 보유하고 있습니다.",
    deadline: "2026-04-30",
    dDay: null,
    views: 6120,
    likes: 134,
    saved: 89,
    source: "삼일회계법인 채용",
    url: "https://www.pwc.com/kr/careers",
  },
  // ── HR ─────────────────────────────────────────────
  {
    id: 20,
    company: "라인플러스",
    logoText: "L",
    gradient: "linear-gradient(145deg, #00B300 0%, #00C300 100%)",
    category: "HR",
    employmentType: "정규직",
    title: "HR Business Partner",
    department: "인사팀",
    location: "분당",
    locationGroup: "경기",
    salary: "4,500 ~ 7,000만원",
    salaryMin: 4500,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["HRM", "채용", "조직문화", "성과관리", "HRIS"],
    requirements: ["HR 실무 경험 3년 이상 (채용/인사관리 포함)", "노동관계법령 이해", "데이터 기반 HR 운영 경험"],
    preferred: ["IT/스타트업 HR 경험", "글로벌 HR 경험", "영어 능통자"],
    mainTasks: ["개발조직 HR BP 역할 수행", "채용 전략 수립 및 핵심 인재 영입", "조직문화·성과관리 체계 운영"],
    benefits: ["해외 워크샵", "스톡옵션", "어학 지원", "원격근무"],
    companyInfo: "라인플러스는 글로벌 메신저 LINE을 운영하는 회사로, 다양한 국적의 인재가 함께 일합니다.",
    deadline: "2026-05-20",
    dDay: null,
    views: 2870,
    likes: 58,
    saved: 31,
    source: "라인플러스 채용",
    url: "https://careers.linecorp.com",
  },
  {
    id: 21,
    company: "쏘카",
    logoText: "S",
    gradient: "linear-gradient(145deg, #00BCD4 0%, #0097A7 100%)",
    category: "HR",
    employmentType: "신입",
    title: "HR 담당자 (신입)",
    department: "인사팀",
    location: "강남",
    locationGroup: "서울",
    salary: "3,200 ~ 4,000만원",
    salaryMin: 3200,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["채용", "교육/훈련", "Excel", "HR 행정"],
    requirements: ["경영학·심리학·사회학 등 관련 전공", "꼼꼼한 업무 처리 능력", "커뮤니케이션 역량"],
    preferred: ["HR 관련 인턴십 경험", "노무관리사/경영지도사 학습 중", "데이터 분석 기초"],
    mainTasks: ["채용 공고 등록 및 서류 전형 운영", "신입·경력사원 온보딩 지원", "인사 행정 업무 (급여·근태 등)"],
    benefits: ["카셰어링 혜택", "유연근무", "자기개발비", "식대"],
    companyInfo: "쏘카는 국내 1위 카셰어링 플랫폼으로, 모빌리티 혁신을 추구하는 스타트업입니다.",
    deadline: "2026-04-20",
    dDay: null,
    views: 4560,
    likes: 89,
    saved: 52,
    source: "쏘카 채용",
    url: "https://socar.career.greetinghr.com",
  },
  // ── 교육 ───────────────────────────────────────────
  {
    id: 22,
    company: "클래스101",
    logoText: "C",
    gradient: "linear-gradient(145deg, #FF6B35 0%, #FF8C00 100%)",
    category: "교육",
    employmentType: "정규직",
    title: "에듀테크 콘텐츠 기획자",
    department: "콘텐츠팀",
    location: "강남",
    locationGroup: "서울",
    salary: "3,800 ~ 5,500만원",
    salaryMin: 3800,
    experience: "경력 1년 이상",
    experienceLevel: "경력",
    skills: ["콘텐츠 기획", "커리큘럼 설계", "영상 제작", "강사 섭외"],
    requirements: ["교육 콘텐츠 기획 또는 제작 경험 1년 이상", "온라인 강의 플랫폼 이해", "커뮤니케이션 능력"],
    preferred: ["에듀테크 업종 경험", "영상 편집 툴 활용 능력", "특정 분야 전문 지식 보유"],
    mainTasks: ["온라인 클래스 기획 및 강사 매칭", "클래스 커리큘럼 구성 및 품질 관리", "학습자 피드백 분석 및 개선"],
    benefits: ["무료 클래스 수강", "유연근무", "자기개발비", "식대"],
    companyInfo: "클래스101은 국내외 100만 명 이상이 이용하는 온라인 클래스 플랫폼입니다.",
    deadline: "2026-04-15",
    dDay: null,
    views: 5670,
    likes: 124,
    saved: 72,
    source: "클래스101 채용",
    url: "https://class101.net/ko/jobs",
  },
  {
    id: 23,
    company: "에듀윌",
    logoText: "E",
    gradient: "linear-gradient(145deg, #1565C0 0%, #1976D2 100%)",
    category: "교육",
    employmentType: "신입",
    title: "교육 콘텐츠 개발자 (신입)",
    department: "콘텐츠개발팀",
    location: "구로",
    locationGroup: "서울",
    salary: "3,000 ~ 3,800만원",
    salaryMin: 3000,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["콘텐츠 기획", "문서 작성", "자격증 지식", "교육학"],
    requirements: ["교육학·사범학부 또는 관련 전공 졸업(예정)자", "자격증 수험 경험 보유자", "꼼꼼하고 정확한 업무 처리"],
    preferred: ["공무원/자격증 시험 합격 경험", "원고 집필 경험", "영상 스크립트 작성 경험"],
    mainTasks: ["자격증·공무원 시험 교재 및 강의 스크립트 개발", "출제 경향 분석 및 문제 제작", "수험생 피드백 반영한 콘텐츠 개선"],
    benefits: ["자격증 취득 지원", "도서비", "건강검진", "유연근무"],
    companyInfo: "에듀윌은 국내 최대 자격증·공무원 교육 전문 기업으로, 꾸준한 성장을 이어가고 있습니다.",
    deadline: "2026-04-30",
    dDay: null,
    views: 3450,
    likes: 67,
    saved: 38,
    source: "에듀윌 채용",
    url: "https://career.eduwill.net",
  },
  // ── 데이터/AI ──────────────────────────────────────
  {
    id: 24,
    company: "SK하이닉스",
    logoText: "SK",
    gradient: "linear-gradient(145deg, #EA1D2C 0%, #FF6B7A 100%)",
    category: "데이터/AI",
    employmentType: "정규직",
    title: "ML 엔지니어 (반도체)",
    department: "AI인프라팀",
    location: "이천",
    locationGroup: "경기",
    salary: "5,000 ~ 8,000만원",
    salaryMin: 5000,
    experience: "경력 3년 이상",
    experienceLevel: "경력",
    skills: ["Python", "PyTorch", "공정 데이터 분석", "시계열 예측"],
    requirements: ["ML/DL 실무 경험 3년 이상", "Python 기반 데이터 분석 역량", "대용량 데이터 처리 경험"],
    preferred: ["반도체 공정 데이터 분석 경험", "시계열 예측 모델 개발 경험", "MLOps 경험"],
    mainTasks: ["반도체 공정 불량 예측 ML 모델 개발", "생산 수율 향상을 위한 AI 솔루션 구축", "대용량 공정 데이터 파이프라인 관리"],
    benefits: ["기숙사 제공", "통근버스", "우리사주", "의료비 지원"],
    companyInfo: "SK하이닉스는 세계 2위 메모리 반도체 기업으로, AI 반도체 시대를 선도하고 있습니다.",
    deadline: "2026-04-07",
    dDay: null,
    views: 4102,
    likes: 79,
    saved: 41,
    source: "SK하이닉스 채용",
    url: "https://recruit.skhynix.com",
  },
  {
    id: 25,
    company: "업스테이지",
    logoText: "U",
    gradient: "linear-gradient(145deg, #7C4DFF 0%, #651FFF 100%)",
    category: "데이터/AI",
    employmentType: "신입",
    title: "AI 엔지니어 (신입)",
    department: "AI Lab",
    location: "강남",
    locationGroup: "서울",
    salary: "4,200만원 ~ (AI 신입 우대)",
    salaryMin: 4200,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["Python", "PyTorch", "LLM", "RAG"],
    requirements: ["AI/ML 관련 전공 졸업(예정)자", "Python 및 PyTorch/TensorFlow 활용 능력", "논문 구현 경험"],
    preferred: ["LLM·생성형 AI 프로젝트 경험", "Kaggle/AI 해커톤 수상 경험", "논문 출판 경험"],
    mainTasks: ["LLM 파인튜닝 및 RAG 파이프라인 개발", "AI 모델 성능 최적화 및 평가", "프로덕트 AI 기능 연구 및 개발"],
    benefits: ["AI 학회 참석 지원", "원격근무", "최신 GPU 장비 지원", "자기개발비"],
    companyInfo: "업스테이지는 국내 대표 AI 스타트업으로, OCR·LLM 등 최첨단 AI 기술을 상용화하고 있습니다.",
    deadline: "2026-05-15",
    dDay: null,
    views: 9870,
    likes: 267,
    saved: 154,
    source: "업스테이지 채용",
    url: "https://upstage.ai/careers",
  },
  // ── 운영/물류 ───────────────────────────────────────
  {
    id: 26,
    company: "CJ대한통운",
    logoText: "CJ",
    gradient: "linear-gradient(145deg, #2196F3 0%, #1565C0 100%)",
    category: "운영/물류",
    employmentType: "신입",
    title: "물류 운영 담당자 (신입)",
    department: "물류운영팀",
    location: "동대문",
    locationGroup: "서울",
    salary: "3,500 ~ 4,200만원",
    salaryMin: 3500,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["물류 관리", "ERP", "Excel", "프로세스 개선"],
    requirements: ["물류·경영·산업공학 등 관련 전공 졸업(예정)자", "분석적 사고 및 문제 해결 능력", "Excel 활용 가능"],
    preferred: ["물류/SCM 인턴십 경험", "ERP 사용 경험", "영어 능통자"],
    mainTasks: ["택배·화물 물류 운영 관리", "KPI 모니터링 및 현황 리포팅", "운영 비효율 발굴 및 프로세스 개선"],
    benefits: ["복지포인트", "건강검진", "사내 동호회", "통근 지원"],
    companyInfo: "CJ대한통운은 국내 1위 종합 물류 기업으로, 글로벌 31개국에 네트워크를 구축하고 있습니다.",
    deadline: "2026-04-25",
    dDay: null,
    views: 3120,
    likes: 48,
    saved: 26,
    source: "CJ대한통운 채용",
    url: "https://recruitment.cjlogistics.com",
  },
  // ── 의료/바이오 ─────────────────────────────────────
  {
    id: 27,
    company: "카카오헬스케어",
    logoText: "KH",
    gradient: "linear-gradient(145deg, #00BFA5 0%, #009688 100%)",
    category: "의료/바이오",
    employmentType: "정규직",
    title: "헬스케어 데이터 분석가",
    department: "데이터사이언스팀",
    location: "판교",
    locationGroup: "경기",
    salary: "5,000 ~ 7,500만원",
    salaryMin: 5000,
    experience: "경력 2년 이상",
    experienceLevel: "경력",
    skills: ["Python", "R", "임상 데이터", "통계", "SQL"],
    requirements: ["의학통계·역학·생명과학 관련 전공 실무 경험 2년 이상", "임상 데이터 분석 경험", "통계 모델링 역량"],
    preferred: ["EMR/PHR 데이터 분석 경험", "디지털 헬스케어 도메인 이해", "논문 게재 경험"],
    mainTasks: ["혈당 관리 서비스 임상 데이터 분석", "의료 AI 모델 성능 검증", "헬스케어 인사이트 리포트 작성"],
    benefits: ["원격근무", "건강검진 강화", "스톡옵션", "연구비 지원"],
    companyInfo: "카카오헬스케어는 AI 기반 혈당 관리 앱 '파스타'를 운영하며 디지털 헬스케어 혁신을 선도합니다.",
    deadline: "2026-05-01",
    dDay: null,
    views: 4320,
    likes: 98,
    saved: 57,
    source: "카카오헬스케어 채용",
    url: "https://kakaohealthcare.com/careers",
  },
  {
    id: 28,
    company: "메디게이트",
    logoText: "MG",
    gradient: "linear-gradient(145deg, #4CAF50 0%, #2E7D32 100%)",
    category: "의료/바이오",
    employmentType: "신입",
    title: "의료 콘텐츠 에디터 (신입)",
    department: "콘텐츠팀",
    location: "서초",
    locationGroup: "서울",
    salary: "3,000 ~ 3,800만원",
    salaryMin: 3000,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["의학 지식", "글쓰기", "리서치", "의학 용어"],
    requirements: ["의학·약학·간호학·생명과학 전공 졸업(예정)자", "의료 전문 글쓰기 역량", "정확한 정보 검증 능력"],
    preferred: ["의학 학술지 번역 경험", "블로그/SNS 의학 콘텐츠 제작 경험", "의사 또는 의료인 자격 소지자"],
    mainTasks: ["의료인 대상 전문 의학 뉴스 편집", "최신 의학 연구 결과 정리 및 기사화", "의약품·시술 정보 콘텐츠 작성"],
    benefits: ["전문직 네트워크", "의학 교육 지원", "유연근무", "건강검진"],
    companyInfo: "메디게이트는 국내 최대 의사 커뮤니티 플랫폼으로, 의료 전문 미디어를 운영합니다.",
    deadline: "2026-04-18",
    dDay: null,
    views: 2780,
    likes: 52,
    saved: 31,
    source: "메디게이트 채용",
    url: "https://medigatenews.com/careers",
  },
  // ── 금융 ───────────────────────────────────────────
  {
    id: 29,
    company: "카카오뱅크",
    logoText: "KB",
    gradient: "linear-gradient(145deg, #FEE500 0%, #FFCA28 100%)",
    category: "재무/회계",
    employmentType: "신입",
    title: "금융 데이터 분석가 (신입)",
    department: "리스크관리팀",
    location: "판교",
    locationGroup: "경기",
    salary: "4,000 ~ 5,000만원",
    salaryMin: 4000,
    experience: "신입",
    experienceLevel: "신입",
    skills: ["SQL", "Python", "통계", "리스크 분석", "Excel"],
    requirements: ["통계·수학·경영학·금융공학 관련 전공 졸업(예정)자", "Python/R 또는 SQL 활용 가능", "데이터 기반 사고력"],
    preferred: ["금융 빅데이터 분석 경험", "통계학/계량경제학 수강 이력", "인턴십 경험"],
    mainTasks: ["여신·수신 상품 데이터 분석", "신용 리스크 모델 개발 보조", "재무 데이터 모니터링 및 리포팅"],
    benefits: ["유연근무", "금융 상품 혜택", "자기개발비", "스톡옵션"],
    companyInfo: "카카오뱅크는 국내 최초 인터넷전문은행으로, IT와 금융의 경계를 허물고 있습니다.",
    deadline: "2026-05-20",
    dDay: null,
    views: 11230,
    likes: 312,
    saved: 198,
    source: "카카오뱅크 채용",
    url: "https://kakaobank.com/careers",
  },
  // ── 게임 ───────────────────────────────────────────
  {
    id: 30,
    company: "넥슨",
    logoText: "Nx",
    gradient: "linear-gradient(145deg, #FF8C00 0%, #FFA500 100%)",
    category: "IT/개발",
    employmentType: "인턴",
    title: "게임 QA 인턴",
    department: "메이플스토리",
    location: "판교",
    locationGroup: "경기",
    salary: "월 200만원",
    salaryMin: 2400,
    experience: "신입/인턴",
    experienceLevel: "신입",
    skills: ["게임 이해도", "버그 리포팅", "테스트 케이스", "문서 작성"],
    requirements: ["게임 QA 또는 테스트에 관심 있는 분", "게임을 즐기는 분", "꼼꼼한 업무 처리 능력"],
    preferred: ["MMORPG 장르 게임 경험", "게임 개발 관련 전공", "버그 리포팅 경험"],
    mainTasks: ["메이플스토리 신규 콘텐츠 QA 테스트", "버그 재현 및 리포트 작성", "테스트 케이스 문서화"],
    benefits: ["게임 아이템 지원", "유연근무", "사내 헬스장", "식대"],
    companyInfo: "넥슨은 메이플스토리·던전앤파이터 등을 보유한 글로벌 게임 기업입니다.",
    deadline: "2026-04-16",
    dDay: null,
    views: 12380,
    likes: 334,
    saved: 198,
    source: "넥슨 채용",
    url: "https://career.nexon.com",
  },
];

// dDay 동적 계산
MOCK_JOBS.forEach((job) => {
  if (job.deadline) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const deadlineDate = new Date(job.deadline);
    const diffMs = deadlineDate - today;
    const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));
    job.dDay = diffDays >= 0 ? diffDays : -1;
  }
});

module.exports = MOCK_JOBS;
